export const  AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTO_LOGOUT = 'AUTO_LOGOUT'
export const REG_SUCCESS = 'REG_SUCCESS'
export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO'
export const GET_DATA = 'GET_DATA'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const EDIT_TASK = 'EDIT_TASK'

